### ISSUE TITLE
Release 2.1 link - instructions

### ISSUE THREAD

**Issue by danielweibel** [ARS-toscana/ConcePTIONAlgorithmPregnancies#10]
@GiorgioLimoncella @RosaMGini 

https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/releases/tag/release_2.1
Instead of description to go to release 2.1?

Why is it not downloadable via green button 'Code' ? Sorry I do not understand these kind of GitHub functionalities. People are used to download scripts with the green 'Code' button. 

Can we put this link in the instructions at:
https://vac4eu.sharepoint.com/:w:/r/sites/Toolbox/Shared%20Documents/07%20Extract-Transform-Load%20(ETL)/DB%20instance%202022_06/Level%20checks%20Instructions%20and%20TEMPLATES/VAC4EU%20ARS%20Pregnancy%20script%20instructions%20AllStudies%20Jul2022.docx?d=w31698e943e5a4029ba153ea3cf3f3737&csf=1&web=1&e=RzyzNw

Thanks Daniel

**Comment by clobart** [comment]
From the green button "Code" you can download the current version of the script, but not the release one.
since we want to be sure that all execute the same version, we "frozen" the script in a release and all the DAPs need to use that one.

I think you have already sent the instructions with th correct link of the release, sorry I didn't see the tag @danielweibel
