### ISSUE TITLE
How can I define the preferred dataset when two sources don't agree?

### ISSUE THREAD

**Issue by DSThayer** [ARS-toscana/ConcePTIONAlgorithmPregnancies#25]
In some cases, I am finding pregnancies that have a birth date in the birth registry (a survey in the CDM), as well as a delivery procedure code in hospital data. The dates differ by a few days.

When this occurs, we need to pick the birth registry date as the correct date. However, it is selecting the procedure date. Is there a way to set parameters so that the birth registry will be considered the gold standard?

**Comment by GiorgioLimoncella** [comment]
It is possible to make a DAP-specific hierarchy, but this should not be the case because the birth registry should already prevail in the hierarchy. 

here is the hierarchy:
![Immagine 2022-08-04 093707](https://user-images.githubusercontent.com/78428400/182791578-98f363fd-998d-4f72-b3f8-012c7cc107d6.png)

I saw that in github the files with the parameters for your datasource are missing, could you please send them so I can check and add them? 

They would be: 

1. 00_parameters_pregnancy.R (in p_parameters_pregnancy)
2. 01_prompts_USWAN.R (in p_parameters_pregnancy/01_prompts)
3. 02_itemsets_USWAN.R (in p_parameters_pregnancy/02_itemsets)
4. 03_conceptsets_USWAN.R (in p_parameters_pregnancy/03_conceptsets)

**Comment by RosaMGini** [comment]
@GiorgioLimoncella this is the first time we run the algorithm on a data source having EUROCAT, is it possible that this triggered a bug that messed with the hierarchy?

**Comment by GiorgioLimoncella** [comment]
yes it is possible! Thanks for the suggestion, I will check it out

**Comment by clobart** [comment]
There was a bug in the creation of the sample, but the content is correct!
