### ISSUE TITLE
step 02_03 - No file LastMenstrualPeriod_implying_pregnancy.RData

### ISSUE THREAD

**Issue by anallg** [ARS-toscana/ConcePTIONAlgorithmPregnancies#32]
Dear @GiorgioLimoncella and @clobart, 

we have a problem executing the step 02_03_T2.2_create_pregnancies_from_itemsets.R. It seems that it needs the file LastMestrualPerior_impliying_pregnancy but it has not been generated in g_intermediate

![image](https://user-images.githubusercontent.com/102151171/186349834-d5a1d2c6-f0e0-4429-8abb-e3c273d18be2.png)

**Comment by GiorgioLimoncella** [comment]
Dear @anallg, 

other dap had the same error and we fixed the bug. 

you should replace the file 02_itemset.R (in the folder p_parameter_pregnancy) and the file step_02_03_T2.2_create_pregnancies_from_itemsets.R (in the folder p_steps_pregnancy). 
The updated version of these steps can be found on github, in branch version_2.0. 
Otherwise you can write to me at giorgio.limoncella@ars.toscana.it and I will email you the files and instructions. 

sorry for the inconvenience!
Giorgio

**Comment by anallg** [comment]
Dear @GiorgioLimoncella, 
do I have  to execute from the beggining again? If I run only 02_3 I have the following error: 
> source(paste0(thisdir,"/p_steps_pregnancy/step_02_03_T2.2_create_pregnancies_from_itemsets.R")) 
Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
In addition: Warning message:
In readChar(con, 5L, useBytes = TRUE) :
  cannot open compressed file 'G:/ConcePTION/RET-VAL/Pregnancy/v5.0_ConcePTIONAlgorithmPregnancies-manuscript/g_intermediate/LastMestrualPeriodImplyingPregnancy.RData', probable reason 'No such file or directory'

**Comment by GiorgioLimoncella** [comment]
Yes! you need to re-run from the beginning. 

to make sure it works I also updated your itemset file, could you replace that too before running? It would be **02_itemsets_BIFAP.R** in p_parameters_pregnancy/02_itemset/
