### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by GiorgioLimoncella** [ARS-toscana/ConcePTIONAlgorithmPregnancies#33]
We noticed that the code O04 ('medical abortion', ICD-10)  is not present in the codelist used in the script. 
However, the code is present in the VAC4EU repository and it is within a range: O00-O06. 
Is it possible that there was an error with the ranges in converting the list? @cduransalinas

**Comment by JR-Farcli** [comment]
Eimir and I we have the same concern. I took a look at the codelist for Elective Termination of Pregnancy, and saw that for example in one row we have as **Narrow O04**; but we also have in another row, **O00-O08 as Possible**. I highlighted these in the Excel attached.
[P_ELECTTERM_AESI.xlsx](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/files/9491471/P_ELECTTERM_AESI.xlsx)

I wonder if one row "cancels" the other (so for example, the script includes O04 because it's narrow, but then removes it because it is found within O00-O08 as possible). Just a wonder, don't know really how the program reads the codelist.

@cduransalinas @eimirh
@GiorgioLimoncella @acidroyo-UMCU

**Comment by RosaMGini** [comment]
dear judit, carlos and albert, 

for us, the 'narrow' definition always wins, it is intended that those codes are inspected with special care (when i doubt you leave 'possible')

@JR-Farcli @cduransalinas we are having a call with coauthors of the pregnancy manuscript tomorrow, could you join? 

we need to make a new release of the pregnancy script, based on the feedback from the DAPs. we have now understood that it is not a problem for us that in some AESIs there are still ranges, because we only use the VAC4EU codelist having Type == "PrA", and there is no range there

so in our new release we would like to use again the codes of the VAC4EU codelist having Type == "PrA". the only requirement is that they must be updated, as follows

  - the codes O04 and O05 need to be added and classified into corresponding Event definitions (arguably, using also the information stored in the AESI ELECTTERM)
  - the codes R15 need to be removed, see [this issue](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/issues/26)
  - the codes W82 need to be reclassified, they are now 'Interruption of pregnancy' but should be classified as 'Spontaneous abortion', see [this issue](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/issues/29)

we see two possible ways forward

  - we are happy to reclassify ourselves, anna and giulia have already worked on sharepoint so they should be able to do this correcly; however, the files of the Event definitions should then be glued together in a single file and claned up, and this is something we cannot do ourselves: is this way feasible?
  - otherwise, we just patch the script manually and wait for a new revision of the codelist to be done together

how do you suggest to proceed?

**Comment by RosaMGini** [comment]
i was forgetting that part of the problem is due to the fact that adding some ICD10 codes requires to go back to codemapper and check if they have new codes in the other coding systems, and then add such codes as well. so, let's decide together how to proceed

**Comment by clobart** [comment]
@giuhye @AnnaGirardi22

**Comment by RosaMGini** [comment]
@JR-Farcli @cduransalinas @eimirh during our validation we foud that ICD9CM code 671 is wrongly labelled as 'birth_narrow': the label is in fact "Venous complications in pregnancy and the puerperium". so the code is 'birth_possile' at best (in fact it refers to puerperium as well). for sure it is not 'birth_narrow'
