### ISSUE TITLE
splitted code in the same folder on SP

### ISSUE THREAD

**Issue by clobart** [ARS-toscana/ConcePTIONAlgorithmPregnancies#37]
Dear @acidroyo-UMCU,

@AnnaGirardi22 @giuhye have splitted some concept sets and have done 2 separated excel sheet for each concept set (inside each folder). This is an example:
![image](https://user-images.githubusercontent.com/38613747/194540067-c86e07f6-f32b-4fa3-9c00-1cc7761f92b8.png)

Is this a problem for the function that put together all the codes inside the folders?
If yes, how do you want to manage the separation of the files?

which is the best way to handle this on purpose of the function?

**Comment by cduransalinas** [comment]
@acidroyo-UMCU, 
today at 4pm, we are going to work with ARS team to get ready the folders in the VAC4EU Sharepoint.
We will come back to you once this is done to generate a new code list. Thank you.

**Comment by GiorgioLimoncella** [comment]
The new code list has been generated, however, the gestation age concepts are missing. 
It seems that after these concepts were updated, the masterfile was not updated with the new concept names and therefore they were not included. 
@cduransalinas can you please check? Many thanks!

**Comment by GiorgioLimoncella** [comment]
Many thanks, here is the list of the new folders, it might come in handy:

   - P_Gestation2526weeksLB_PrA_Gestation 25 26 weeks
   
   - P_Gestation2526weeksUNK_PrA_Gestation 25 26 weeks unknown
    
   - P_Gestation2728weeksLB_PrA_Gestation 27 28 weeks LB
    
   - P_Gestation2728weeksUNK_PrA_Gestation 27 28 unknown
    
   - P_Gestation2930weeksLB_PrA_Gestation 29 30 weeks LB
    
   - P_Gestation2930weeksUNK_PrA_Gestation 29 30 weeks Unknown
     
   - P_Gestation3132weeksLB_PrA_Gestation 31 32 weeks LB
    
   - P_Gestation3132weeksUNK_PrA_Gestation 31 32 weeks Unknown
    
   - P_Gestation3334weeksLB_PrA_Gestation 33 34 weeks
     
   - P_Gestation3334weeksUNK_PrA_Gestation 33 34 UNK
     
   - P_Gestation3536weeksLB_PrA_Gestation 35 36 weeks LB
     
   - P_Gestation3536weeksUNK_PrA_Gestation 35 36 UNK
    
   - P_Gestation37weeksLB_PrA_Gestation 37 weeks LB
    
   - P_Gestation37weeksUNK_PrA_Gestation 37 UNK
    
   - P_24weeksUNK_PrA_24 weeks pregnancy unknown
    
   - P_Gestationlessthan24weeks**L**_PrA_Gestation less than 24 weeks LB (is L instead of LB, otherwise the maximum length for excel sheets is exceeded)
    
   - P_Gestationlessthan24weeksU_PrA_Gestation less than 24 weeks UNK

**Comment by cduransalinas** [comment]
I have included all new names into the master file on the Vac4EU SP. 
The list can be produced again.
Thank you.

**Comment by GiorgioLimoncella** [comment]
Many thanks @cduransalinas!
@acidroyo-UMCU could you please update the full code list? Now it should include all the concepts. 
thank you!

**Comment by acidroyo-UMCU** [comment]
Dear all,

Here you have the updated code list:

https://vac4eu.sharepoint.com/sites/Toolbox/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FToolbox%2FShared%20Documents%2F08%20Event%20%26%20Covariate%20definitions%2FDiagnosisCodeSheet%2FCombined%20codelist%2F14%20October%202022&viewid=8c361874%2D61d2%2D40c1%2Db4cf%2De3e1de20abec

Best,
Albert

From: GiorgioLimoncella ***@***.***>
Reply to: ARS-toscana/ConcePTIONAlgorithmPregnancies ***@***.***>
Date: Thursday, 13 October 2022 at 10:21
To: ARS-toscana/ConcePTIONAlgorithmPregnancies ***@***.***>
Cc: "Cid Royo, A. (Albert)" ***@***.***>, Mention ***@***.***>
Subject: Re: [ARS-toscana/ConcePTIONAlgorithmPregnancies] splitted code in the same folder on SP (Issue #37)


Many thanks @cduransalinas<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcduransalinas&data=05%7C01%7CA.CidRoyo%40umcutrecht.nl%7C219ce47664c64e741e0108daacf3e8d4%7Cdcdf4a3dd0c04a6394cf781981249be5%7C0%7C0%7C638012460833184632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OHOmgjHAG2CKpqKa8qHBv2MiTNZoVYHNTF5bHwxi%2F80%3D&reserved=0>!
@acidroyo-UMCU<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Facidroyo-UMCU&data=05%7C01%7CA.CidRoyo%40umcutrecht.nl%7C219ce47664c64e741e0108daacf3e8d4%7Cdcdf4a3dd0c04a6394cf781981249be5%7C0%7C0%7C638012460833184632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zco0aH55VLl87Q0TmkcOoVZ8vahmTASrcEWfzJHBrbQ%3D&reserved=0> could you please update the full code list? Now it should include all the concepts.
thank you!

—
Reply to this email directly, view it on GitHub<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FARS-toscana%2FConcePTIONAlgorithmPregnancies%2Fissues%2F37%23issuecomment-1277224858&data=05%7C01%7CA.CidRoyo%40umcutrecht.nl%7C219ce47664c64e741e0108daacf3e8d4%7Cdcdf4a3dd0c04a6394cf781981249be5%7C0%7C0%7C638012460833184632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4KYuku1EdMgWdn2CNVzWAHS3c3UaKdMsKWTAlzBsKRQ%3D&reserved=0>, or unsubscribe<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAY7H4G5O2XAWBG4DOBNEFCDWC7A7TANCNFSM6AAAAAAQ7PVNRQ&data=05%7C01%7CA.CidRoyo%40umcutrecht.nl%7C219ce47664c64e741e0108daacf3e8d4%7Cdcdf4a3dd0c04a6394cf781981249be5%7C0%7C0%7C638012460833184632%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vJG%2B1YDn4J6RJWVV%2FxGFbE5k8KC%2BptpXAUjXFsI4dd4%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

------------------------------------------------------------------------------

De informatie opgenomen in dit bericht kan vertrouwelijk zijn en is
uitsluitend bestemd voor de geadresseerde. Indien u dit bericht onterecht
ontvangt, wordt u verzocht de inhoud niet te gebruiken en de afzender direct
te informeren door het bericht te retourneren. Het Universitair Medisch
Centrum Utrecht is een publiekrechtelijke rechtspersoon in de zin van de W.H.W.
(Wet Hoger Onderwijs en Wetenschappelijk Onderzoek) en staat geregistreerd bij
de Kamer van Koophandel voor Midden-Nederland onder nr. 30244197.

Denk s.v.p aan het milieu voor u deze e-mail afdrukt.

------------------------------------------------------------------------------

This message may contain confidential information and is intended exclusively
for the addressee. If you receive this message unintentionally, please do not
use the contents but notify the sender immediately by return e-mail. University
Medical Center Utrecht is a legal person by public law and is registered at
the Chamber of Commerce for Midden-Nederland under no. 30244197.

Please consider the environment before printing this e-mail.

**Comment by GiorgioLimoncella** [comment]
@cduransalinas  @acidroyo-UMCU 
excel is messing up the format of the codes and we would like to download the list directly in csv. 
From share point however we can't do it, is there any way to get the list directly into csv? 
Thanks, Giorgio

**Comment by giuhye** [comment]
Dear @cduransalinas and @acidroyo-UMCU,

we did not find in the 20221013_V2_ALL_full_codelist the following event_abbreviation although they are included in the master file:

-Gestationlessthan24weeksL
-Gestationlessthan24weeksU
-Gestation2728weeksUNK
-Gestation3132weeksUKN

@GiorgioLimoncella and i also split the file named "P_24weeksL_PrA" into "P_24weeksLB_PrA" and "P_24weeksUNK_PrA". Could you please update the master file and generate the new codelist?

Best,
Giulia and Giorgio

**Comment by GiorgioLimoncella** [comment]
@cduransalinas @acidroyo-UMCU 

@giuhye  and I have temporarily included the missing codes in the script one by one. 
If fixing the codes in the share point takes too long we can still make the release with this correction and update it later. 
Anyway, to do this we would still need access to the file in csv format!
