### ISSUE TITLE
new data for UOSL

### ISSUE THREAD

**Issue by jingzhuio** [ARS-toscana/ConcePTIONAlgorithmPregnancies#44]
@clobart @GiorgioLimoncella 
Dear Claudia and Giorgio,
We are using a different set of data for the next report and we also try to transform the CDM tables the way as it should. I sent our updated ETL to Giorgio's email 'giorgio.limoncella@unifi.it' as my email can not be delivered to ars email address. Please let me know if there's any changes other than in the instructions I need to do before running the script. Many many thanks! Best, Jing

**Comment by GiorgioLimoncella** [comment]
hi Jing, 

sorry for the late reply, I checked your ETL and it looks like some parameters have changed. Maybe we could have a meeting to check everything together?

About luigi, I think I don't have to give him access, a tag should be enough (@LAMaglan) 

Best, 
Giorgio

**Comment by jingzhuio** [comment]
@LAMaglan @GiorgioLimoncella 
No worries at all. A meeting sounds good. If you and Luigi are both available and prefer tomorrow, feel free to have the meeting without me. Otherwise I'm available on Thursday all day and Friday all day except 11-12.   Best, Jing

**Comment by LAMaglan** [comment]
@jingzhuio I think it is best if you are in the meeting, since you actually know/understand the ETL.
If you want me to join, I am available on thursday after 12, or anytime on friday (except 11-12).

@GiorgioLimoncella I am not sure if you are aware, but UiO/UOSL/NORWAY has "similar" data (sources) for
ConcePTION, CONSIGN and VAC4EU, but with different ETLs, and the pregnancy algorithm is
being used for all three of these projects.

**Comment by LAMaglan** [comment]
@jingzhuio I think it is best if you are in the meeting, since you actually know/understand the ETL.
If you want me to join, I am available on thursday after 12, or anytime on friday (except 11-12).

@GiorgioLimoncella I am not sure if you are aware, but UiO/UOSL/NORWAY has "similar" data for
ConcePTION, CONSIGN and VAC4EU, but with different ETLs, and the pregnancy algorithm is
being used for all three of these projects.

**Comment by jingzhuio** [comment]
@LAMaglan @GiorgioLimoncella
Fair enough. I can join myself then.:) 
Giorgio, feel free to schedule a meeting! I will show you a more up-to-dated ETL at the meeting as we might be doing some changes during the level checks. Best, Jing

**Comment by RosaMGini** [comment]
> @GiorgioLimoncella I am not sure if you are aware, but UiO/UOSL/NORWAY has "similar" data (sources) for
> ConcePTION, CONSIGN and VAC4EU, but with different ETLs, and the pregnancy algorithm is
> being used for all three of these projects.

dear @LAMaglan, it would be very important if we could spend some time in clarifying this. 

according to the ConcePTION pipeline, ETL should stay stable across instances and studies. minor exceptions may be: a table/column is missing in an instance, or a column is renamed, or the type of a column changes (eg from exact date to approximated dates). this does indeed impose a minor modification in the ETL - but at the *design* level, the ETL should stay the same. however, i understand that you may find yourself in situations that make this impossible, is this correct?

would it be possible for you to illustrate for us the reasons why you may decide to change your ETL design? this would be very valuable for us. thanks!

**Comment by GiorgioLimoncella** [comment]
Hi @RosaMGini, 
the ETL is now aligned with the other instances/studies, thanks!

@LAMaglan @jingzhuio
