### ISSUE TITLE
EpiChron : Error in step_05_03_predictive_model.R

### ISSUE THREAD

**Issue by bpoblador** [ARS-toscana/ConcePTIONAlgorithmPregnancies#83]
Dear @GiorgioLimoncella 

I obtain an error in predictive model after several rounds: 

![image](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/assets/99145664/0f65117c-2854-4587-ad5c-438a76a6232d)

Can you help me to solve it? Thanks!

**Comment by GiorgioLimoncella** [comment]
Hi @bpoblador, 

Thank you for reporting the error. 

We are implementing a new release (5.2) in which we update the list of diagnosis codes and make other changes. I will include the correction of this error in that release and update you as soon as the release is ready!

**Comment by danielweibel** [comment]
@GiorgioLimoncella 
Thank you very much Giorgio! We need to produce results for the Pfizer study and need to plan. Until when would you be able to fix it? 
Thanks again for your support!!
Daniel

**Comment by GiorgioLimoncella** [comment]
Hi @danielweibel, 

This error should already be fixed. However, we are in the process of updating the codelist since some DAPs have requested to add ICD9 and ICD10CM codes. 

You can download the corrected version (without the updated code list) at this link: 

https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/archive/refs/heads/version_5.1.zip 

Otherwise in a few days (I hope) version 5.2 will be published in the release section, which will also contain the updated code list. 

Giorgio

**Comment by danielweibel** [comment]
@GiorgioLimoncella this is excellent, thank you very much!!
@bpoblador please download the [corrected algorithm script](https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/archive/refs/heads/version_5.1.zip) and run as soon as possible.

Thank you,
Best regards
Daniel
