### ISSUE TITLE
Sample of pregnancies to check does not include person ID of pregnant woman

### ISSUE THREAD

**Issue by DSThayer** [ARS-toscana/ConcePTIONAlgorithmPregnancies#84]
The CSV file sample of pregnancies to check should include the person ID of the pregnant woman. This is needed to link back to the source data and actually investigate whether the pregnancy output is correct.

It would be great if this could be included in the next version.

**Comment by RosaMGini** [comment]
hi Dan, this is not included on purpose, because the file may happen to be shared.

But, you can use a separate file to identify the person ID. Look at the instructions linked in this page

https://github.com/ARS-toscana/ConcePTIONAlgorithmPregnancies/wiki/Instructions-to-validate-the-pregnancy-algorithm

You can find  the information you need at the end of the file, under the header 'Additional controls'.

In case of need, please don't hesitate do be back to us

**Comment by DSThayer** [comment]
Hi Rosa,

Thanks for the response. I'm aware that it can be obtained from the RData file, and used that in the past. I just thought it would be a lot easier to include it in the check file itself. I didn't realize that was done for a governance/safety reason.

Best regards,
Dan
